Check for PQfformat
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/sqlclient/trunk@19733 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4242,6 +4242,81 @@ if test "$POSTGRES" = "yes"; then
   fi
 
 
+echo "$as_me:$LINENO: checking for PQfformat in -lpq" >&5
+echo $ECHO_N "checking for PQfformat in -lpq... $ECHO_C" >&6
+if test "${ac_cv_lib_pq_PQfformat+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpq  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char PQfformat ();
+int
+main ()
+{
+PQfformat ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pq_PQfformat=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pq_PQfformat=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pq_PQfformat" >&5
+echo "${ECHO_T}$ac_cv_lib_pq_PQfformat" >&6
+if test $ac_cv_lib_pq_PQfformat = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPQ 1
+_ACEOF
+
+  LIBS="-lpq $LIBS"
+
+fi
+
+  if test "$ac_cv_lib_pq_PQfformat" != "yes"; then
+      POSTGRES=
+
 echo "$as_me:$LINENO: checking for PQclear in -lpq" >&5
 echo $ECHO_N "checking for PQclear in -lpq... $ECHO_C" >&6
 if test "${ac_cv_lib_pq_PQclear+set}" = set; then
@@ -4314,11 +4389,15 @@ _ACEOF
 
 fi
 
-  if test "$ac_cv_lib_pq_PQclear" != "yes"; then
-      POSTGRES=
-      echo "******************************************************"
-      echo "Unable to locate postgres pq library (is it installed)"
-      echo "******************************************************"
+      if test "$ac_cv_lib_pq_PQclear" != "yes"; then
+	echo "******************************************************"
+	echo "Unable to locate postgres pq library (is it installed)"
+	echo "******************************************************"
+      else
+	echo "******************************************************"
+	echo "Located postgres pq library, but it is too old to use!"
+	echo "******************************************************"
+      fi
   fi
 
 echo "$as_me:$LINENO: checking for ECPGconnect in -lecpg" >&5
